/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.footer[_ngcontent-%COMP%] {\r\n  background: #212121;\r\n  color: white;\r\n  padding: 30px 0px;\r\n\r\n}\r\n\r\n.container[_ngcontent-%COMP%] {\r\n  display: flex;\r\n}\r\n\r\n.container[_ngcontent-%COMP%]   .angular[_ngcontent-%COMP%] {\r\n  display: block;\r\n  margin-top: 10px;\r\n}\r\n\r\n.container[_ngcontent-%COMP%]   .angular[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\r\n  height: 30px;\r\n  margin-right: 10px;\r\n}\r\n\r\n\r\n\r\n.container[_ngcontent-%COMP%]   p[_ngcontent-%COMP%], .container[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] {\r\n  width: 50%;\r\n}\r\n\r\n.container[_ngcontent-%COMP%]   .share[_ngcontent-%COMP%] {\r\n  text-align: right;\r\n}\r\n\r\n.sb-style[_ngcontent-%COMP%] {\r\n  margin: 0px !important;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
