/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './footer.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../node_modules/ngx-sharebuttons/components/share-buttons/share-buttons.component.ngfactory';
import * as i3 from 'ngx-sharebuttons/components/share-buttons/share-buttons.component';
import * as i4 from './footer.component';
const styles_FooterComponent:any[] = [i0.styles];
export const RenderType_FooterComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_FooterComponent,data:{}});
export function View_FooterComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),20,'div',[['class',
      'footer']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          17,'div',[['class','container']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n\n        '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),8,'p',[['class','copyright']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n            Copyright BuchmannDesign 2017'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n            '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),3,'span',
          [['class','angular']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n                '])),(_l()(),
          i1.ɵeld(0,(null as any),(null as any),0,'img',[['alt','angular logo'],['src',
              'assets/angular.png']],(null as any),(null as any),(null as any),(null as any),
              (null as any))),(_l()(),i1.ɵted((null as any),[' Powered by Angular\n            '])),
      (_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵted((null as any),
          ['\n\n\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',
          [['class','share']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n            '])),(_l()(),
          i1.ɵeld(0,(null as any),(null as any),1,'share-buttons',([] as any[]),(null as any),
              (null as any),(null as any),i2.View_ShareButtonsComponent_0,i2.RenderType_ShareButtonsComponent)),
      i1.ɵdid(638976,(null as any),0,i3.ShareButtonsComponent,([] as any[]),{linkedIn:[0,
          'linkedIn'],tumblr:[1,'tumblr'],pinterest:[2,'pinterest'],whatsApp:[3,'whatsApp']},
          (null as any)),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵted((null as any),
          ['\n\n\n\n      '])),(_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵted((null as any),
          ['\n\n\n\n']))],(_ck,_v) => {
    const currVal_0:any = false;
    const currVal_1:any = false;
    const currVal_2:any = false;
    const currVal_3:any = false;
    _ck(_v,17,0,currVal_0,currVal_1,currVal_2,currVal_3);
  },(null as any));
}
export function View_FooterComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-footer',([] as any[]),
      (null as any),(null as any),(null as any),View_FooterComponent_0,RenderType_FooterComponent)),
      i1.ɵdid(114688,(null as any),0,i4.FooterComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const FooterComponentNgFactory:i1.ComponentFactory<i4.FooterComponent> = i1.ɵccf('app-footer',
    i4.FooterComponent,View_FooterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9zaXRlcy9DbG91ZFRWMy9zcmMvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC50cy5Gb290ZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiZm9vdGVyXCI+XG4gICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuXG4gICAgICAgIDxwIGNsYXNzPVwiY29weXJpZ2h0XCI+XG4gICAgICAgICAgICBDb3B5cmlnaHQgQnVjaG1hbm5EZXNpZ24gMjAxNzxiciAvPlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJhbmd1bGFyXCI+XG4gICAgICAgICAgICAgICAgPGltZyBzcmM9XCJhc3NldHMvYW5ndWxhci5wbmdcIiBhbHQ9XCJhbmd1bGFyIGxvZ29cIj4gUG93ZXJlZCBieSBBbmd1bGFyXG4gICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgIDwvcD5cblxuXG4gICAgICAgIDxkaXYgY2xhc3M9XCJzaGFyZVwiPlxuICAgICAgICAgICAgPHNoYXJlLWJ1dHRvbnMgW3BpbnRlcmVzdF09XCJmYWxzZVwiIFtsaW5rZWRJbl09XCJmYWxzZVwiIFt0dW1ibHJdPVwiZmFsc2VcIiBbd2hhdHNBcHBdPVwiZmFsc2VcIj48L3NoYXJlLWJ1dHRvbnM+XG4gICAgICAgIDwvZGl2PlxuXG5cblxuICAgICAgPC9kaXY+XG5cbjwvZGl2PlxuXG5cblxuIiwiPGFwcC1mb290ZXI+PC9hcHAtZm9vdGVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBb0IsMkNBQ2hCO1VBQUE7VUFBQSw4QkFBdUI7TUFFbkI7VUFBQTtNQUFxQjtNQUNZO1VBQUEsMERBQU07VUFBQSxxQkFDbkM7VUFBQTtVQUFBLGdCQUFzQix1REFDbEI7aUJBQUE7Y0FBQTtjQUFBLGdCQUFpRDtNQUM5QywrQ0FDUDtVQUFBLHFCQUdKO1VBQUE7VUFBQSxnQkFBbUIsbURBQ2Y7aUJBQUE7Y0FBQTthQUFBO1VBQUE7VUFBQSxlQUEwRywrQ0FDeEc7VUFBQSxxQkFJRix5Q0FFTjtVQUFBO0lBUHlDO0lBQW1CO0lBQXZDO0lBQXdEO0lBQXZFLFlBQW1DLFVBQW1CLFVBQXZDLFVBQXdELFNBQXZFOzs7O29CQ1paO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
