/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.card[_ngcontent-%COMP%] {\r\n  margin-top: 20px;\r\n}\r\n\r\n.card-body[_ngcontent-%COMP%] {\r\n  padding: 30px;\r\n}\r\n\r\n\r\ninput.ng-touched.ng-invalid[_ngcontent-%COMP%] {\r\n  border: 2px solid red;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9jaGFubmVsLWZvcm0vY2hhbm5lbC1mb3JtLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9jaGFubmVsLWZvcm0vY2hhbm5lbC1mb3JtLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
