/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.card[_ngcontent-%COMP%] {\r\n  margin-top: 40px;\r\n}\r\n\r\n.card-body[_ngcontent-%COMP%] {\r\n  padding: 30px;\r\n}\r\n\r\nh2[_ngcontent-%COMP%] {\r\n  margin-bottom: 30px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9sb2dpbi9sb2dpbi5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3NpdGVzL0Nsb3VkVFYzL3NyYy9hcHAvbG9naW4vbG9naW4uY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
