/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['div.edit[_ngcontent-%COMP%] {\r\n  display: inline-block;\r\n  float: right;\r\n}\r\n\r\nimg.channellogo[_ngcontent-%COMP%] {\r\n  margin-right: 15px;\r\n  width: 30px;\r\n  height: 30px;\r\n}\r\n\r\n.manager[_ngcontent-%COMP%]   .leftcolumn[_ngcontent-%COMP%] {\r\n  margin-top: 30px;\r\n}\r\n\r\n.manager[_ngcontent-%COMP%]   .channels[_ngcontent-%COMP%] {\r\n  margin-top: 30px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9tYW5hZ2VyL21hbmFnZXIuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9zaXRlcy9DbG91ZFRWMy9zcmMvYXBwL21hbmFnZXIvbWFuYWdlci5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
