/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['[_nghost-%COMP%] {\r\n\r\n\r\n}\r\n\r\nimg.channellogo[_ngcontent-%COMP%] {\r\n  width: 30px;\r\n  height: 30px;\r\n}\r\n\r\np[_ngcontent-%COMP%] {\r\n  font-size: 14px;\r\n}\r\n\r\n.card-block[_ngcontent-%COMP%] {\r\n  padding-left: 15px;\r\n  padding-right: 0px;\r\n}\r\n\r\n.devicelogo[_ngcontent-%COMP%] {\r\n  padding: 10px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovc2l0ZXMvQ2xvdWRUVjMvc3JjL2FwcC9kZXZpY2VzL2RldmljZXMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9zaXRlcy9DbG91ZFRWMy9zcmMvYXBwL2RldmljZXMvZGV2aWNlcy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
